FROM node:18

WORKDIR /dockerapp

# Copy only necessary files (node_modules excluded via .dockerignore)
COPY . .

# Install dependencies inside the container
RUN npm install

# Build the app for production
RUN npm run build

# Install the 'serve' package globally to serve the built app
RUN npm install -g serve

# Expose port 5173 (or whatever port you use)
EXPOSE 5173

# Serve the built app
CMD ["serve", "-s", "dist", "-l", "5173"]
